### ISSUE TITLE
Why not use es6/7 for this boilerplate?

### ISSUE THREAD

**Issue by sibelius** [IBM-Blockchain/fabric-boilerplate#23]
I think es6/7 provides a much more readable code, also we could use async/await syntax to query the blockchain instead of callback hell

**Comment by czar0** [comment]
Hi @sibelius, thanks for the suggestions here and in #25 and #21. We are working on a new version of the boilerplate which will includes the following features:
- AngularJS (2) TypeScrypt going to substitute its older brother
- NodeJS completely rewritten in TypeScript
- Unit testing (for Angular, NodeJS and chaincode)
- An _install_ script to assist the user in setting up the environment
- Better SoC between server, client and blockchain
- And more

In addition, the boilerplate will run on separated Docker containers, respectively for the server, client and blockchain network, in order to prevent issues related to different systems and configurations.

So, stay tuned! :)

**Comment by sibelius** [comment]
I'm going in another direction

- Flow to type check
- GraphQL to expose blockchain api
- Unit testing using Jest
- React for the frontend

I'll try to release it in the end of january 

tks for the hard work on this boilerplate, it is really helpful

**Comment by sibelius** [comment]
I've just release a bolerplate using es6/7 and graphql as well

check it out
https://github.com/entria/hyperledger-fabric-graphql-boilerplate

**Comment by arner** [comment]
Great work sibelius, thanks for sharing
